logging:
  level:
    root: INFO              # în loc de DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
#    net.ttddyy.dsproxy: DEBUG
#    root: DEBUG
#    org.springframework: DEBUG
#    org.springframework.web: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE  # paramètres SQL
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.engine.transaction.internal: DEBUG
#    org.hibernate.orm.jdbc.extract: TRACE
#    com.zaxxer.hikari: DEBUG   # connection pool
#    org.flywaydb: DEBUG

# application.yml  (default = H2)
spring:
  profiles:
    active: h2
  datasource:
    proxy:
      logging: SLF4J
      multiline: true
      json-format: false
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none # flyway is used for validation
    properties:
      hibernate.jdbc.time_zone: UTC
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000   # optional
    publisher-confirm-type: correlated   # optional
    publisher-returns: true              # optional
    #retry listener
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          max-interval: 10000
          multiplier: 2
    #retry producer
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000

  mail:
    host: smtp.gmail.com
    port: 587
    username: mereuta.marian@gmail.com
    password: test

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    # pentru JSON converter (opțional dacă îl ai ca bean)
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false

    locations: classpath:db/migration
server:
  servlet:
    context-path: /api/v1
  port: 8080


---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/salon?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:salon}
    password: ${DB_PASS:salon}
    driver-class-name: com.mysql.cj.jdbc.Driver
