package training.salonzied.error;

public enum ErrorCode {
  ENTITY_NOT_FOUND,
  CONFLICT,
  BUSINESS_RULE_VIOLATION,
  VALIDATION_ERROR,
  CONSTRAINT_VIOLATION,
  BAD_REQUEST,
  METHOD_NOT_ALLOWED,
  UNSUPPORTED_MEDIA_TYPE,
  DATA_ACCESS_ERROR,
  UNEXPECTED_ERROR,
  UNPROCESSABLE_ENTITY,
}
